apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-dashboard-ingress
  namespace: longhorn-system
  annotations:
    ingressclass: "traefik"  # Specifies Traefik as the ingress controller
spec:
  rules:
    - host: longhorn.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80