apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learn-nginx-ingress
  namespace: learn
  annotations:
    ingressclass: "traefik"  # Specifies Traefik as the ingress controller
spec:
  rules:
    - host: nginx.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80