apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-deployment
  namespace: budget
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget
  template:
    metadata:
      labels:
        app: budget
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: budget-data
          persistentVolumeClaim:
            claimName: budget-pvc
      containers:
        - name: budget
          image: actualbudget/actual-server:26.2.0-alpine # only latest is available
          ports:
            - containerPort: 5006
          env:
            - name: NODE_ENV
              value: "production"
          volumeMounts:
            - name: budget-data
              mountPath: /data
          resources:
            requests:
              memory: "20Mi"
              cpu: "10m"
              ephemeral-storage: "2Gi"
            limits:
              memory: "100Mi"
              cpu: "50m"
              ephemeral-storage: "10Gi"