apiVersion: v1
kind: Service
metadata:
  name: budget-service
  namespace: budget
spec:
  selector:
    app: budget
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5006
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budget-ingress
  namespace: budget
  annotations:
    ingressclass: "traefik"  # Specifies Traefik as the ingress controller
spec:
  rules:
    - host: budget.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budget-service
                port:
                  number: 80
