apiVersion: v1
kind: Service
metadata:
  name: budget-service
  namespace: budget
spec:
  selector:
    app: budget
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5006
  type: ClusterIP
