apiVersion: v1
kind: Service
metadata:
  name: excalidraw-service
  namespace: simpletools
spec:
  selector:
    app: excalidraw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excalidraw-ingress
  namespace: simpletools
  annotations:
    ingressclass: "traefik"  # Specifies Traefik as the ingress controller
spec:
  rules:
    - host: excalidraw.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: excalidraw-service
                port:
                  number: 80
